import json
import sys

# Pulls the confused records from a file generated by stats.py

if sys.argv[len(sys.argv)-1] != sys.argv[0]:
	file = open(sys.argv[len(sys.argv)-1], 'rb')
	errorfile = open(sys.argv[len(sys.argv)-1]+"confused.txt", 'wb')
else:
	sys.exit("No filename supplied!")

stats = json.load(file)
for r in stats["confused"]:
	errorfile.write(r[0]["key"]+"\t"+str(r[1])+"\n")